application: clutchindia-187410
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

